### ISSUE TITLE
This is incredible! Mind sharing your Alfred Workflow?

### ISSUE THREAD

**Issue by gitatmax** [lanewinfield/zoomout#1]

**Comment by lanewinfield** [comment]
Thanks! It's in the repo!

https://github.com/lanewinfield/zoomout/blob/main/alfred%20workflow/zoomout-alfred.alfredworkflow

**Comment by gitatmax** [comment]
Can't believe I missed that, thanks!

**Comment by macin23** [comment]
Hello
